package dev.tmmc.reservity.reservations.dto;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.Instant;

/**
 * Body for {@code POST /api/spaces/{slugOrId}/reservation-requests}.
 *
 * <p>Per M5 plan: backend accepts the minimum the frontend sends today
 * ({@code startsAt}, {@code endsAt}, optional {@code recurring}) and applies
 * sensible defaults for {@code attendeesCount}, {@code tag}, etc.</p>
 *
 * @param recurring "none" (default) or "weekly" — biweekly accepted by the
 *                  schema but not generated by M5.
 */
public record CreateReservationRequest(
        @NotNull Instant startsAt,
        @NotNull Instant endsAt,
        String recurring,                 // "none" | "weekly"
        @Size(max = 500) String purpose,
        @Min(1) @Max(1000) Integer attendeesCount,
        @Size(max = 40) String contactPhone,
        String tag                         // ReservationTag display string
) {}
